### DISCUSSION TITLE
How to parse and serialize custom tags

### DISCUSSION THREAD

**Discussion by miffels** [eemeli/yaml#268] [Q&A] [answered]
Hey,

I have a situation where I am transforming a YAML document that has some custom tags in it. I would like to preserve the tags, but I haven't found a way to write them out the same way I received them. So in essence, the flow is `YAML.parse` --> modify object --> `YAML.stringify`. Note that I have read https://eemeli.org/yaml/v1/#custom-data-types.

YAML document:

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

If I fail to supply any `custom_tags` in the YAML options for `YAML.parse`, `YAML.stringify` turns this into

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: ""
      emoji_generator: ""
```

I tried to supply custom types like so

```ts
  const twemojiType = {
    identify: () => false,
    tag: 'tag:yaml.org,2002:python/name:materialx.emoji.twemoji',
    resolve: () => '!!python/name:materialx.emoji.twemoji',
    stringify: () => '!!python/name:materialx.emoji.twemoji',
  };
  const toSvgType = {
    identify: () => false,
    tag: 'tag:yaml.org,2002:python/name:materialx.emoji.to_svg',
    resolve: () => '!!python/name:materialx.emoji.to_svg',
    stringify: () => '!!python/name:materialx.emoji.to_svg',
  };

  const yamlOpts = {
    customTags: [
      twemojiType,
      toSvgType,
    ],
  };
  const config = YAML.parse(yamlString, yamlOpts);
  // ...
  YAML.stringify(config);
```

But then the tag is just rendered as a string:

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: "!!python/name:materialx.emoji.twemoji"
      emoji_generator: "!!python/name:materialx.emoji.to_svg"
```

Any ideas?
