### DISCUSSION TITLE
Document Add/Set/Delete values deep in the YAML?

### DISCUSSION THREAD

**Discussion by 5chrisalexander** [eemeli/yaml#355] [Q&A] [answered]
```
a:
  b:
    c:
      key1: value1
```
If I have a Document (doc) that represents the above YAML, I want to be able to add a key/value pair next to key1, like this:
```
a:
  b:
    c:
      key1: value1
      key2: value2
```
To do this, I'd think I could do 
`doc.add({key:'a.b.c.key2', value:'value2'})` or `doc.set('a.b.c.key2','value2')`
However, when I do that I get a Document that toString()s like this:

```
a:
  b:
    c:
      key1: value1
a.b.c.key2: value2
```

Is there a way to do deep adds/sets/deletes?

Thanks!

**Comment by 5chrisalexander** [comment]
Here's the part where I sort of answer my own question after doing some more playing around:
`doc.setIn(['a','b','c','key2'],'value2')` 
gives me 
```
a:
  b:
    c:
      key1: value1
      key2: value2
```
However, if I wanted to set 'a.d.e.key3' like:
```
a:
  b:
    c:
      key1: value1
      key2: value2
  d:
    e:
      key3: value3
```
This comes out looking like:
```
a:
  b:
    c:
      key1: value1
      key2: value2
  !!omap
  - d:
      !!omap
      - e:
          !!omap
          - key3: value3
```

**Comment by eemeli** [comment, marked as answer]
This should work, at least with `yaml@next`?

```yaml
# src
a:
  b:
    c:
      key1: value1
```

```js
import { parseDocument } from 'yaml'

const doc = parseDocument(src)
doc.setIn(['a','b','c','key2'], 'value2')
doc.setIn(['a','d','e','key3'], 'value3')
```

```yaml
# doc.toString()
a:
  b:
    c:
      key1: value1
      key2: value2
  d:
    e:
      key3: value3
```
