### DISCUSSION TITLE
How to create an empty node?

### DISCUSSION THREAD

**Discussion by gajus** [eemeli/yaml#364] [Q&A]
This is the desired result:

```yaml
metadata:
  labels:
  # {{ include "app.resource_labels" . | indent 4 }}
```

Note that `labels` does not have a value.

This is a valid YAML, though I don't see a way to create it using this API.
