### DISCUSSION TITLE
Stringify: Is it possible to overwrite the type of specific elements?

### DISCUSSION THREAD

**Discussion by Kirdock** [eemeli/yaml#365] [Q&A] [answered]
If I have the object: 
```js
{
  name: 'myName'
  freeText: 'this is my free text'
}
```
and strinfigy it (`Yaml.stringify(myObj)`), is it possible to overwrite the type of one property? So everything should be `PLAIN` except `freeText`, which should be `BLOCK_FOLDED`.

```yaml
name: myName
freeText: >
    this is my free text
```

**Comment by eemeli** [comment, marked as answer]
Yes. You'll need to first construct a Document from your JS value, and then set the type of the appropriate node. This is how it looks like with `yaml@next`:

```js
import { Document } from 'yaml'
const doc = new Document({ name: 'myName', freeText: 'this is my free text\n' })
doc.get('freeText', true).type = 'BLOCK_FOLDED'
doc.toString()
```

```yaml
name: myName
freeText: >
  this is my free text
```
