### DISCUSSION TITLE
Preserve newlines of sequence indicator (`-`) when `YAML.Document.toString()`?

### DISCUSSION THREAD

**Discussion by kuanyui** [eemeli/yaml#406] [Q&A] [answered]
I need to use `const doc = YAML.parseDocument()` to parse + modify lots of `.yaml` files, and they have lots of sequence looks like this:

```yml
# This is comments
characters:
  -
    id: 0
    name: "Ib"
    age: 5
    items:
      - "rose"
      - "red ribbons"
      - "book"
  -
    id: 1
    name: "Garry"
    age: 20
    items:
      - "coat"
      - "spider on head"
  -
    id: 666
    name: "Mary"
    age: 5
    items:
      - "whatever"
```
But when I `doc.toString()`, the sequence become:

```yml
# This is comments
characters:
  - id: 0
    name: "Ib"
    age: 5
    items:
      - "rose"
      - "red ribbons"
      - "book"
  - id: 1
    name: "Garry"
    age: 20
    items:
      - "coat"
      - "spider on head"
  - id: 666
    name: "Mary"
    age: 5
    items:
      - "whatever"
```

**I don't want to modify the coding styles of the original `*.yaml` files as possible as it can (for the readability for human beings)**, is there any option to keep these new lines at the beginning of an object (map / collection / `-`)  ? Thanks.
