### DISCUSSION TITLE
null value rendered as ? fieldname instead of fieldname: null

### DISCUSSION THREAD

**Discussion by naivefun** [eemeli/yaml#410] [Q&A]
```
query:
  opt_pretty: true
  # some comments
  opt_fields: 1
  # opt_fields: 1
path:
  ? attachment_gid
```

The attachment_gid is null, if use stringify it looks ok but lose comments. How to fix this? Thanks.
