### DISCUSSION TITLE
How to parse then serialize a yaml with tags/intrinsic functions transparently to allow modification to Cloudformation script

### DISCUSSION THREAD

**Discussion by alshdavid** [eemeli/yaml#433] [Q&A] [answered]
Cloudformation scripts can become monolithic and huge, I am looking for a solution to break them up into smaller, more manageable pieces. Preprocessing them with `yaml` seems like a possible solution - however I am having trouble with CF intrinsic functions.

My hope is to split a main CF file into multiple:

```yaml
# main.cloudformation.yaml
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Type: String
```

```yaml
# s3.cloudformation.yaml
Resources:
  S3BucketWebAssets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BucketName}'
```

Where the expected output from my combiner:

```yaml
# Expected output
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Type: String

Resources:
  S3BucketWebAssets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BucketName}'
```

I was hoping I could do something as simple as:

```js
const fs = require('node:fs')
const path = require('node:path')
const YAML = require('yaml')

const mainContants = fs.readFileSync(path.join(__dirname, 'main.cloudformation.yaml'))
const bucketContants = fs.readFileSync(path.join(__dirname, 's3.cloudformation.yaml'))

const main = YAML.parse(mainContants)
const s3 = YAML.parse(bucketContants)

const result = main
result.Resources = {
   ...s3.Resources
}

console.log(YAML.stringify(result))
```

However, `yaml` throws on CF intrinsic functions (like `!Sub` and `!Ref`) and doesn't parse the yaml file. I would like `yaml` to ignore them entirely during parsing and reinsert them during serialization.

Can this be achieved?
