### DISCUSSION TITLE
Stringify: My merge keys are surrounded with quotes ""

### DISCUSSION THREAD

**Discussion by alexbjorlig** [eemeli/yaml#438] [Q&A] [answered]
I attempt to stringify this object with `stringify(//, {schema: 'yaml-1.1'})`:
```
{
  name: "test",
  model: [
    { name: "general information", cc: { ['<<']: "*section"} },
  ]
}
```

I get this: 

```
name: v4
model:
  - name: General information
    cc:
      <<: "*section"
```

But the above does not work, because `*section` is surrounded with `"`. How can I fix this?
