### DISCUSSION TITLE
Is it possible to make toJSON not insert null for no value

### DISCUSSION THREAD

**Discussion by gee4vee** [eemeli/yaml#442] [Q&A]
If I have a yaml like this (note no value for `name`):

```
  - name:
    module_type: terraform
    source:
      source_type: github
      git:
        git_repo_url: 'https://github.ibm.com/gvalenc/environment-aio-iks-app-us/tree/master/IBM-Observability'
    inputs:
      - name: logdna_name
        value: $blueprint.logdna_name
      - name: logdna_region
        value: $blueprint.region
      - name: provision_at
        value: $blueprint.provision_at
      - name: at_name
        value: $blueprint.at_name
      - name: at_region
        value: $blueprint.region
      - name: resource_group_id
        value: $module.bp-iks-resource-group.outputs.resource_group_id
    outputs:
      - name: logdna_crn
      - name: logdna_id
      - name: at_crn
      - name: at_id
```

The result of `parseDocument(...).toJSON()` is this:

```
    {
      name: null,
      module_type: 'terraform',
      source: [Object],
      inputs: [Array],
      outputs: [Array]
    },
```

Is it possible to not insert a `null` when no value is supplied to the property in the yaml? The reason I ask is because I'm converting the YAML to JSON and validating it with a schema and the null gives an unhelpful error message for `name`:

```
 Expected `null` (null) in `#/modules/1/name` to be of type `string`
```

Ideally I would get a missing required property error instead.
