### DISCUSSION TITLE
Unable to print an unquoted YAML

### DISCUSSION THREAD

**Discussion by FStefanni** [eemeli/yaml#456] [Q&A] [answered]
Hi,

I have a JSON document.
What I want is to read the document, and write it back as a proper YAML.
This means:
- write sequences and objects as blocks
- do not use quotes for keys

So I tried:

```javascript
const json = YAML.parseDocument(jsonObject);
const content = YAML.stringify(
            json,
            {
                "blockQuote": true,
                "collectionStyle": "block",
                "defaultKeyType": YAML.Scalar.PLAIN,
                "defaultStringType": YAML.Scalar.BLOCK_LITERAL,
                "doubleQuotedAsJSON": true,
                "indentSeq": true
            }
        );
```

But it did not work, since the output is something as:
```yaml
  "network-2":        // <--- Please note the undesired quotes on the keys! :(
    "external":
      "name": "network-2"
```

I desire something as:
```yaml
  network-2:        // <--- No quotes on keys! :)
     external:
      name: "network-2"
```

I tried also a lot of different combinations, but no success.

Another idea could be to maybe iterate over all tree objects, and somehow force the node styles as PLAIN (I suppose),
But it is to me not obvious how to iterate over the nodes.

Any idea/help please?

Regards
