### DISCUSSION TITLE
How to add a [key: alias] node to a map?

### DISCUSSION THREAD

**Discussion by slhck** [eemeli/yaml#470] [Q&A] [answered]
I have a map and, somewhere else, I have some anchors defined.

I would like to change the name of an anchor, then change the alias that references it to use new name. This works.

But I would like to also add a new entry to the map, and make it reference that anchor.

Here is what I have so far:

```typescript
import YAML, { isAlias, isMap } from "yaml";

const TEST_YAML_STRING = `
my_custom_schedules:
  custom_schedule: &custom_schedule_alias
    foo: bar

my_config:
  default: &default
    foo: baz
  my-c-005: *default
  my-c-006: *custom_schedule_alias
`;

const document = YAML.parseDocument(TEST_YAML_STRING);
const customSchedules = document.get("my_custom_schedules");
if (isMap(customSchedules)) {
  const customSchedule = customSchedules.get("custom_schedule");
  if (isMap(customSchedule)) {
    // change the name of the anchor
    customSchedule.anchor = "new_custom_schedule_anchor";
  }
}

const config = document.get("my_config");
if (isMap(config)) {
  // change the existing C006 alias to point to the new anchor
  const myC006 = config.get("my-c-006");
  if (isAlias(myC006)) {
    myC006.source = "new_custom_schedule_anchor";
  }

  // create a new alias for C007 to point to the anchor
  config.add({ key: "my-c-007", value: "???" });
}

const documentStr = document.toString();
```

I would expect the following:

```yaml
my_custom_schedules:
  custom_schedule: &new_custom_schedule_anchor
    foo: bar

my_config:
  default: &default
    foo: baz
  my-c-005: *default
  my-c-006: *new_custom_schedule_anchor
  my-c-007: *new_custom_schedule_anchor
```

But how do I add `my-c-007` with the correct alias?
