### DISCUSSION TITLE
How do I edit a yaml file and keep new lines?

### DISCUSSION THREAD

**Discussion by KungWaz** [eemeli/yaml#473] [Q&A] [answered]
If I want to edit the provided yaml file below and keep the empty new line, for readability, how would I do that?
Currently when I use the parser and then save it back to the same file when I have edited it the new line between the devices and items blocks is removed.

Code:
````
import { parse } from "yaml";
import fs from "fs";

const path = "./.github/workflows/main.yml";
const file = fs.readFileSync(path);
const yaml = parse(file.toString());

yaml["devices"]["laptop"]["name"] = "asus";

fs.writeFileSync(path, stringify(yaml, { lineWidth: 0 }));
````

YAML:
````
devices:
  laptop:
    name: not_set
  desktop:
    name: dell

items:
  keyboard:
    name: not_set
  mouse:
    name: logitech
````

Result:
````
devices:
  laptop:
    name: asus
  desktop:
    name: dell
items:
  keyboard:
    name: not_set
  mouse:
    name: logitech
````

Expected:
````
devices:
  laptop:
    name: asus
  desktop:
    name: dell

items:
  keyboard:
    name: not_set
  mouse:
    name: logitech
````
