### DISCUSSION TITLE
How do I add/set an array as the value of a key?

### DISCUSSION THREAD

**Discussion by rennerg** [eemeli/yaml#478] [Q&A]
I'm working with Kubernetes yaml definitions and need to insert the following yaml block into an existing file (note the `command` key/value pair):

```yaml
...
spec:
  template:
    spec:
      initContainers:
        - name: container-name
          image: image-name@sha:123abc
          command: ["/bin/sh", "-c", "ls", "/ifu/en"]
...
```

The code I'm using to insert this block is
```js
doc.addIn(['spec', 'template', 'spec', 'initContainers', 0], {
        name: 'container-name',
        image: 'image-name@sha:123abc',
        command: ["/bin/sh", "-c", "ls", "/ifu/en"]
    });
```
which is producing this yaml:
```yaml
...
spec:
  template:
    spec:
      initContainers:
        - name: container-name
          image: image-name@sha:123abc
          command: 
            - /bin/sh
            - -c
            - ls
            - /ifu/en
...
```
I've tried various things and nothing seems to give me what I need. Is what I'm trying to do possible?
Thanks
