### DISCUSSION TITLE
How to traverse CST upward from a Token?

### DISCUSSION THREAD

**Discussion by vanessadnguyen** [eemeli/yaml#597] [General]
Hi,
I found Scalar token using CST.visit and match its key.source to a given name. From that token, I have a need to traverse upward to the root to collect the path from the root to the token. How do I do that?
For example,
```
validations:
  - expression: ''
    messageExpression: ''
    reason: ''
```
```
CST.visit(token, (item, path) => {
          if (CST.isScalar(item.key) && item.key.source === 'messageExpression') {
            res = item.key;
            // NOTE: path here does not seem to help me much. It is an array of tuples ['value', someNumber]
            const parent = CST.visit.parentCollection(token, path);
            const parent1 = CST.visit.parentCollection(item, path);
            return CST.visit.BREAK;
          }
        }); // end of CST.visit
```
The result of the upward traversal should return a path array as **['validations', 0, 'messageExpression']**

**Comment by eemeli** [comment]
For that sort of use, you're probably better off using `keepSourceTokens: true` and the AST visitor, as its `path` contains the actual ancestor nodes.

The CST isn't guranteed to be valid YAML, so it might be dealing with a document that looks like this:
```
validations: 42
validations:
  - expression: ''
    messageExpression: ''
    reason: ''
```

With that sort of input, e.g. the top-level parent of the `messageExpression: ''` pair needs to be referred to not by its key, but by its index in the array representing that collection; that's what the path indices are referring to. The first `'key' | 'value'` is a pointer to whether the node is on the "key" or "value" side of mapping pairs.
