### ISSUE TITLE
SyntaxError: Sequence items are not allowed on the same line with map keys

### ISSUE THREAD

**Issue by ikatyang** [eemeli/yaml#10]
Sorry for the bad title, I'm not sure how to name this issue.

**version:**
1.0.0-beta.6

**input:**

(extract from https://github.com/prettier/prettier/blob/d0cd112/.circleci/config.yml)

```yaml
aliases:
  - restore_cache:
      - v1-yarn-cache
  - save_cache:
      paths:
        - ~/.cache/yarn
  - &restore_deps_cache
    keys:
      - v1-deps-cache-{{ checksum "yarn.lock" }}
```

**output:**

```
SyntaxError: Sequence items are not allowed on the same line with map keys (7:3)
  5 |       paths:
  6 |         - ~/.cache/yarn
> 7 |   - &restore_deps_cache
    |   ^^^^^^^^^^^^^^^^^^^^
> 8 |     keys:
    | ^^^^^^^^^
> 9 |       - v1-deps-cache-{{ checksum "yarn.lock" }}
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**expected:**

no error.

P.S. It parses correctly if there's no indentation:

```yaml
aliases:
- restore_cache:
    - v1-yarn-cache
- save_cache:
    paths:
      - ~/.cache/yarn
- &restore_deps_cache
  keys:
    - v1-deps-cache-{{ checksum "yarn.lock" }}
```

**Comment by eemeli** [comment]
This is a frankly ludicrous corner case that you've managed to find. Will dig into this a bit more later, but here's the minimal case that I've been able to break it down to:
```yaml
  - a
  - b:
    - c
  - d
```
If you remove any part of that, the bug is not triggered.

**Comment by ikatyang** [comment]
Tried on the current master 024e81d9121d28e23ba3d8ae73dfe9e562d8c732, the case mentioned above is fixed, but if I tried to parse the entire file (https://github.com/prettier/prettier/blob/d0cd112/.circleci/config.yml) it fails again, it seems the entire file should be a good test case.

Here's the minimal failed part (probably):

```yaml
aliases:
- save_cache:
    paths:
      - ~/.cache/yarn
    key: v1-yarn-cache
- keys:
```

```
SyntaxError: Sequence items are not allowed on the same line with map keys (6:1)
  4 |       - ~/.cache/yarn
  5 |     key: v1-yarn-cache
> 6 | - keys:
    | ^^^^^^^
  7 | 
```
