### ISSUE TITLE
Directive formatting in output

### ISSUE THREAD

**Issue by acklavidian** [eemeli/yaml#112]
Is there anyway to have the `---` (directive maybe?) at the top of the document on stringification?'
eg:
```yaml
---
description: 'i do not know what that thing up there at the top is called'
possibly:
  - directive
  - triple dash
  - separator  
...
```
