### ISSUE TITLE
Setting value inside a document

### ISSUE THREAD

**Issue by cambiph** [eemeli/yaml#121]
Consider the following YAML:

```yaml
version: 2
plan:
  project-key: WEBCO
  key: abc
  name: Bamboo spec

triggers:
  - polling: 130

variables:
  release_version: patch

stages:
  - Build:
      jobs:
        - Build
  - Release:
      manual: true
      jobs:
        - Release

Build:
  key: BD
  tasks:
    - clean
    - script:
        scripts:
          - 'docker-compose -f test/docker-compose.yml up --exit-code-from tests'
          - /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

Release:
  key: REL
  tasks:
    - clean
    - script:
        scripts:
          - /opt/scripts/git/git-repository-information-restore.sh
  requirements:
    - REMOTE_ONLY
...

version: 2
plan:
  key: abc
  
plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
      - permissions:
          - view
          - edit
          - build
```

I am trying to parse the document and change some fields but I keep getting `TypeError: doc.set is not a function`

```javascript
const file = fs.readFileSync(path.join(__dirname, 'templates/template.yml'), { encoding: 'utf8'});
const doc = yaml.parseAllDocuments(file);
doc.set('version', 'test)
```

Can you please tell me what I am doing wrong because I cannot abstract that from the docs?
Thanks in advance.

Regards

**Comment by eemeli** [comment]
The return type of `YAML.parseAllDocuments()` is an array of documents; in your example there are two of them. Try calling eg. `doc[1].set()`.

**Comment by cambiph** [comment]
> The return type of `YAML.parseAllDocuments()` is an array of documents; in your example there are two of them. Try calling eg. `doc[1].set()`.

I feel very dumb right now, I even read that in the docs but the penny didn't drop :s

**Comment by cambiph** [comment]
Using the method you mentioned above, I can successfully edit the Documents.
When I stringify the array of Documents, the resulting YAML is actually a Map and not two Documents , seperated by ..., as I would assume.

```javascript
const file = fs.readFileSync(path.join(__dirname, 'templates/template.yml'), { encoding: 'utf8'});
const doc = yaml.parseAllDocuments(file);

const spec = doc[0];
const permissions = doc[1];
const specPlan = spec.get('plan');
const permissionPlan = permissions.get('plan')

specPlan.set('key', planKey);
specPlan.set('name', planName);
permissionPlan.set('key', planKey);
```
```yaml
- version: 2
  plan:
    project-key: WEBCO
    key: ABC
    name: Bamboo spec
  triggers:
    - polling: 130
  variables:
    release_version: patch
  stages:
    - Build:
        jobs:
          - Build
    - Release:
        manual: true
        jobs:
          - Release
  Build:
    key: BD
    tasks:
      - clean
      - script:
          scripts:
            - docker-compose -f test/docker-compose.yml up --exit-code-from tests
            - /opt/scripts/docker/stop-docker-containers.sh
    requirements:
      - REMOTE_ONLY
  Release:
    key: REL
    tasks:
      - clean
      - script:
          scripts:
            - /opt/scripts/git/git-repository-information-restore.sh
            - /opt/scripts/docker/stop-docker-containers.sh
    requirements:
      - REMOTE_ONLY
- version: 2
  plan:
    key: ABC
  plan-permissions:
    - groups:
        - bamboo-admin
        - bamboo-release
        - developer-admin
        - permissions:
            - view
            - edit
            - build
            - clone
            - admin
```
