### ISSUE TITLE
Error reading AWS SAM CLI generated template.yaml

### ISSUE THREAD

**Issue by ot-tony-archer** [eemeli/yaml#129]
AWS SAM CLI generates a yaml file.  Because AWS, they like double-colon formatting for some strings.  These blow up the reader.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-world

  Sample SAM Template for hello-world
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

. . .
```

See line 2.

This causes `yaml` to blow up with: 

```sh
~/lambdas/hello-world/template.yaml:2
Transform: AWS::Serverless-2016-10-31
               ^

SyntaxError: Unexpected token ':'
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/tarcher/code/sam-theta/routes/index.js:11:30
    at Array.map (<anonymous>)
    at /Users/tarcher/code/sam-theta/routes/index.js:10:31
    at Layer.handle [as handle_request] (/Users/tarcher/code/sam-theta/node_modules/express/lib/router/layer.js:95:5)
```

Is there an easy way around this?  Clearly I can't change the AWS yaml as a solution.

EDIT:  Also, the Description blows it up as well because of the `>` symbol.
