### ISSUE TITLE
Is there an "Indent Children" Argument for Formatting

### ISSUE THREAD

**Issue by devstein** [eemeli/yaml#143]
From what I understand, `prettier` uses this package to format `yaml` files but the default it formats by given children the same indentation as their parent.

```yaml
parent:
- child: 1
- child: 2
```

But I would like the format to indent all children:

```yaml
parent:
    - child: 1
    - child: 2
```

Is there a flag for this? Or is this specific to the the `prettier` project. 

For reference, I want to use this project for autoformatting but maintain the behavior of `yaml_formatter_indent_collection` flag in the [vim-yaml-formatter](https://github.com/tarekbecker/vim-yaml-formatter#configuration)
