### ISSUE TITLE
Duplicate comment when converting back from document

### ISSUE THREAD

**Issue by zoroaster00** [eemeli/yaml#18]
The yaml will contain duplicate comment when converting the parsed document by "toString"
Example:

```
test1:
  foo: #123
    bar: 1
```
After parseDocuments and doc.toString()
```
test1:
  foo: #123
    #123
    bar: 1
```
