### ISSUE TITLE
How could join two YAML document?

### ISSUE THREAD

**Issue by gixlg** [eemeli/yaml#218]
Hi all,
I have a input YAML like this one (`input.yml`):
```
lev1:
  lev2:
    A: "a"
    ### Comment ###
    B: "b"
    C: "c"
    ### Something ###
    ### Another comment ###
    D: "d"
    ### blablabla ###
```
and a Yaml snipet like this other (`new.yml`)

```
### New staff ###
E: 'e'
F: 'f'
### End new staff ###
```

I want to obtain an output document joining these two YAMLs, adding the snipet under `lev2`.
The desired result is this one:

```
lev1:
  lev2:
    A: "a"
    ### Comment ###
    B: "b"
    C: "c"
    ### Something ###
    ### Another comment ###
    D: "d"
    ### blablabla ###
    ### New staff ###
    E: 'e'
    F: 'f'
    ### End new staff ###
```

I've tried in this way:
```
const doc = YAML.parseDocument(fs.readFileSync('input.yml', 'utf8'))
const newStaff = YAML.parseDocument(fs.readFileSync('new.yml', 'utf8'));

let lev2 = doc.get('lev1').get('lev2');
lev2.add(newStaff)
console.log(String(doc));
```

but in output I got this:

```
lev1:
  lev2:
    A: "a"
    ### Comment ###
    B: "b"
    C: "c"
    ### Something ###
    ### Another comment ###
    D: "d"
    E: e
      F: f: null
    ### blablabla ###
```

not what I expected.

Why is that?
How can I do to get the expected result?
