### ISSUE TITLE
Object wrappers for primitives may not be stringified correctly

### ISSUE THREAD

**Issue by MikeRalphson** [eemeli/yaml#236]
**Describe the bug**
JavaScript types `Boolean`, `Number` and `String` (wrappers for primitive types) are stringified very differently to in JSON when invoked with `new`.

**To Reproduce**

```js
const yaml = require('yaml');

const o = { enum: [] };
o.enum.push(new String('mystring'));
o.bool = new Boolean(false);
o.num = new Number(123);

console.log(JSON.stringify(o));

console.log(yaml.stringify(o));
```

**Expected behaviour**

```yaml
enum:
  - mystring
bool: false
num: 123
```

not

```yaml
enum:
  - - m
    - y
    - s
    - t
    - r
    - i
    - n
    - g
bool: {}
num: {}
```

**Versions (please complete the following information):**

- Environment: Node v14.15.1
- `yaml`: 2.0.0-3

**Additional context**

`JSON.stringify` returns `{"enum":["mystring"],"bool":false,"num":123}`

Unsure if this is really a bug in the default operation, or whether the behaviour could be controlled via an option. Does not happen when the `new` keyword is not used.
