### ISSUE TITLE
Comment on the last line is moved on the line above

### ISSUE THREAD

**Issue by gixlg** [eemeli/yaml#277]
Considering this yml **input**
```
environment:
  ### SESSION START ###
  A: "true"
  B: "true"
  ### SESSION END ###
```

if the document is parsed and then printed out the result is not the same, but the comment goes on the same line as _'B'_.

```
const file = fs.readFileSync('./test/input/config.yml', 'utf8')
const doc = YAML.parseDocument(file)
doc.toString()
```

**output**
```
environment:
  ### SESSION START ###
  A: "true"
  B: "true" ### SESSION END ###
```

**Expected behaviour**
I would like to preserve the positioning of the comment. There is a way to achieve it?

**Versions:**

- Environment: 
- Node.js: v12.14.0
- yaml: 2.0.0-5

**Comment by eemeli** [comment]
Are you sure that this is happening with the example that you posted above? I'm not able to replicate this behaviour:

```js
const doc = YAML.parseDocument(`environment:
  ### SESSION START ###
  A: "true"
  B: "true"
  ### SESSION END ###
`)

doc.toString()
> 'environment:\n' +
  '  ### SESSION START ###\n' +
  '  A: "true"\n' +
  '  B: "true"\n' +
  '  ### SESSION END ###\n'
```

I don't doubt that end-comment placement is problematic, so this may well be a dupe of #244.

**Comment by gixlg** [comment]
Oh yeah, my bad I haven't reported an important detail apparently: **The empty line at the end of the input**.

```
const doc = YAML.parseDocument(`environment:
  ### SESSION START ###
  A: "true"
  B: "true"
  ### SESSION END ###

`);

doc.toString()
> 'environment:\n' +
  '  ### SESSION START ###\n' +
  '  A: "true"\n' +
  '  B: "true" ### SESSION END ###\n'

```
Here the project to reproduce it: https://stackblitz.com/edit/test-yml

This use case is useful for me when there are ymls more complex and space and line comment can be used to gain more clarity.
```
environment:
  ### SESSION START ###
  A: "true"
  B: "true"
  ### SESSION END ###

  ### ANOTHER SESSION START ###
  C: "true"
  D: "true"
  ### ANOTHER SESSION END ###
  
```
like this example above.
