### ISSUE TITLE
Parser reports false positive error on yaml with anchors 

### ISSUE THREAD

**Issue by evidolob** [eemeli/yaml#284]
**Describe the bug**
When parser parses this yaml:
```yaml
default: &DEFAULT
  name: Anchor
customname: &CUSTOMNAME
  custom_name: Anchor
anchor_test:
  <<: *DEFAULT
  <<: *CUSTOMNAME
```

It reports error: `Map keys must be unique`. But this is valid yaml.

**To Reproduce**
Just parse yaml provided in description.

**Expected behaviour**
Parser shouldn't report duplicate key errors on anchor references. 

**Versions (please complete the following information):**

- Environment:  `Node.js 12.7.0` 
- `yaml`: `2.0.0-6`

**Additional context**
Found during work on https://github.com/redhat-developer/yaml-language-server/pull/442
