### ISSUE TITLE
More elegant dynamic replacement

### ISSUE THREAD

**Issue by JacBian** [eemeli/yaml#327]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/8401855/140005081-66889142-fcbb-4939-8655-2d9c64cd2ac4.png)

![image](https://user-images.githubusercontent.com/8401855/140005169-c1c2dfd5-8cc4-464b-9cd7-fa37f2a85f34.png)

Is it possible to set specific syntax, define placeholders in the YAML template, and then pass in an option that matches the locator as an input parameter

**Comment by JacBian** [comment]
Just idea

**Comment by eemeli** [comment]
It should be relatively easy for you to build such a template post-processor with a [visitor](https://eemeli.org/yaml/#modifying-nodes) that walks through the YAML document's contents.

In order to consider the library itself providing such functionality, this behaviour would need to be rather well specified, and preferably already used in more than one context.

**Comment by JacBian** [comment]
Perhaps it makes more sense to define a Template String, because yamL doesn't support such a definition. By customizing placeholders, the file itself is no longer standard YAML and has lost its universal meaning.

**Comment by JacBian** [comment]
```
var yamlStr = `
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app: ${deployment.name}
          name: ${deployment.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ${deployment.name}
          template:
            metadata:
              labels:
                app: ${deployment.name}
            spec:
              containers:
                - image:${deployment.image}
                  name:  ${deployment.name}
                  ports:
                    - containerPort: ${deployment.Port}
        `
```
