### ISSUE TITLE
Standalone comments seem to be left out when using YAML.parse()

### ISSUE THREAD

**Issue by thomasqbrady** [eemeli/yaml#330]
When using YAML.parse() to parse a document that has standalone single-line comments, the comments seem to be stripped out.

I am passing this YAML input:
```
tokens:
  butter:
    # values in the `base` name space are not able to be overridden
    base:
      color:
        heb_red: &heb_red
          type: color
          overridable: false
          category: brand
```

to YAML.parse(), and I'm getting back a document that does not have any comments in it.

- Environment: Node.js v16.2.0
- `yaml`: 2.0.0-8
