### ISSUE TITLE
Full Support For Block Sequences Missing

### ISSUE THREAD

**Issue by crowmagnumb** [eemeli/yaml#339]
**Describe the bug**
The block sequence in yaml is not properly supported.

**To Reproduce**

From this [Example](https://www.tutorialspoint.com/yaml/yaml_block_sequences.htm)

```yml
port: &ports
  adapter:  postgres
  host:     localhost

development:
  database: myapp_development
  <<: *ports
```

```js
import YAML from yaml;
console.log(YAML.parse(ymltext));
```

The output should be ...
```json
{
   "port": {
      "adapter": "postgres",
      "host": "localhost"
   },
   "development": {
      "database": "myapp_development",
      "adapter": "postgres",
      "host": "localhost"
   }
}
```

But instead I get ...

```
{
  port: { adapter: 'postgres', host: 'localhost' },
  development: {
    database: 'myapp_development',
    '<<': { adapter: 'postgres', host: 'localhost' }
  }
}
```

**Expected behaviour**

The output as shown in the example.

**Versions (please complete the following information):**

- Environment:  Node v16.10.0
- `yaml`: 1.10.2
