### ISSUE TITLE
Empty map values are round-tripped to `null`

### ISSUE THREAD

**Issue by GeorchW** [eemeli/yaml#366]
**Description:** Empty map values are not round-tripped correctly.

**To reproduce:**

```js
parseDocument("nothing:").toString()
// expected output: "nothing:"
// actual output:   "nothing: null\n"
```

**Versions:**

- Environment: Node.js v16.13.1
- `yaml`: 2.0.0-10

**Additional context**

Thanks a lot for this awesome library! I'm using it to edit around in docker-compose files, where the pattern 

```yaml
volumes:
  a-volume:
  another-volume:
```

is quite common. These are currently round-tripped to

```yaml
volumes:
  a-volume: null
  another-volume: null
```

If there is more content after the `volumes` block, it's getting worse, where this

```yaml
volumes:
  a-volume:

networks: "whatever"
```

is round-tripped to this:

```yaml

volumes:
  a-volume:

    null
networks: "whatever"
```

There are other minor offenders to round-tripping (like a tiny bit of whitespace preservation here and there), but this is the only offender that is very visible. I can probably refer to the CST for my use-cases, but this might be something you want to look at.
