### ISSUE TITLE
Incorrect parsing of ansible playbook (YAML) while using jinja templatings

### ISSUE THREAD

**Issue by priyamsahoo** [eemeli/yaml#477]
We are using the library for parsing YAML docs in the [Ansible Language Server](https://github.com/ansible/ansible-language-server).

**Describe the bug**
Recently, while migrating from 1.x to 2.x, we noticed that the parser could not parse a yaml doc correctly when it contains jinja templatings, which it used to do earlier.

**To Reproduce**
Consider this playbook:
```yaml
- name: A play to test vars
  hosts: localhost
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: "hello {{  }}"
      vars:
        task_var: world
```
In this case, using `parseDocument` function and logging `doc.contents` gives the following:
```
YAMLSeq {
  items: [ YAMLMap { items: [Array], range: [Array] } ],
  range: [ 0, 178, 178 ]
}
```

Now, here's where it fails:

Consider this playbook. The only difference is that we remove the quotes around `hello {{  }}`, which is still a valid yaml syntax:
```yaml
- name: A play to test vars
  hosts: localhost
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: hello {{  }}
      vars:
        task_var: world
```
In this case, using `parseDocument` function and logging `doc.contents` gives the following:
```
YAMLSeq {
  items: [ YAMLMap { items: [Array], range: [Array] } ],
  range: [ 0, 137, 137 ]
}
```
This is incorrect, as the range's end value is not the end of the document. The parsing doesn't read anything after the curly braces.

**Expected behavior**
In the second scenario, the range of the document should not change, and `contents` should have the entire document.

**Versions (please complete the following information):**

- Environment: Node v18.15.0
- `yaml`: 2.2.2

**Additional context**
This used to give correct results while we were using yaml v1.10.0, and the problem only started after we migrated to yaml v2.x.
