### ISSUE TITLE
Inconsistent comments handling for empty nodes 

### ISSUE THREAD

**Issue by roman-burdeiniy** [eemeli/yaml#491]
**Describe the bug**
Inconsistent behaviour of parseDocument function.
Once yaml contains deep hierarchical of empty nodes the comment from the next node on a top level is getting ignored. Instead it appears on a wrong level of hierarchy. See example below.

**To Reproduce**
Consider yaml
```
SettingsMenuPopup:

  #@desc: Colours for settings button by modes.
  iconColor:
    open:

  #@desc: Settings button configuration.
  #@class: Button
  button:
```
Use `const document = yaml.parseDocument(fileSource, { sortMapEntries: true });`

**Expected behaviour**
The comment "@desc: Settings button configuration.\n@class: Button" should be on "button" Scalar on level:
`document.contents.items[0].value.items[1].value.comment`.

<img width="1187" alt="Screenshot 2023-08-09 at 10 03 25" src="https://github.com/eemeli/yaml/assets/6292761/50f79f32-1f6f-4100-af27-a568c5a6786c">

**Actual behaviour**
The comment "@desc: Settings button configuration.\n@class: Button" appears on "iconColor.open" level Scalar:
`document.contents.items[0].value.items[0].value.items[0].value.comment`.

<img width="1159" alt="Screenshot 2023-08-09 at 10 12 53" src="https://github.com/eemeli/yaml/assets/6292761/8b87408e-dffa-4abf-8d2f-832c1d150399">

**Versions (please complete the following information):**

- Environment: [e.g. Node.js 14.7.0 or Chrome 87.0]
Node v20.0.0
- `yaml`: [e.g. 1.10.0 or 2.0.0-2]
    2.3.1
   According to my local tests the bug was introduced in [2.0.0-4](https://github.com/eemeli/yaml/releases/tag/v2.0.0-4)

**Additional context**
The issue will be solved if I explicitly apply `null` to empty node in yaml, e.g.
```
SettingsMenuPopup:

  #@desc: Colours for settings button by modes.
  iconColor:
    open: null

  #@desc: Settings button configuration.
  #@class: Button
  button:
```
