### ISSUE TITLE
Strings using \r do not get serialized with | notation

### ISSUE THREAD

**Issue by LeaVerou** [eemeli/yaml#492]
Hi @eemeli, it's been a while! 👋🏼 Just stumbled on this library of yours, thanks for making it!

Here’s a testcase of the issue: https://codepen.io/leaverou/pen/Rwqzadv

Input is:
```json
{
	"language": "html",
	"code": "<label>Username:\r\n<input name=\"username\">\r\n</label>"
}
```

Expected output:
```yaml
language: html
code: |-
  <label>Username:
  <input name="username">
  </label>
```

Actual output of YAML.stringify:
```yml
language: html
code: "<label>Username:\r

  <input name=\"username\">\r

  </label>"
```

This happens even when `defaultStringType: "BLOCK_LITERAL"` (it seems to only affect `language: html`.

When the `\r`s are removed, it produces the correct result.
