### ISSUE TITLE
commentBefore seems to be assigned to wrong node

### ISSUE THREAD

**Issue by EloB** [eemeli/yaml#502]
**Describe the bug**
See title.

**To Reproduce**
[Steps to reproduce the behaviour.](https://codesandbox.io/s/hungry-tree-q3hdmg?file=/src/index.ts:0-368)

```js
import yaml from "yaml";

const ast = yaml.parseDocument(/* YAML */ `
# Before example
example:
  # Before C
  c: hello
  # Before A
  a: world
  # Before B
  b: yaml
`);

ast
  .get("example")
  .items.sort((a, b) => a.key.value.localeCompare(b.key.value));

console.log(ast.toString());
```

**Expected behaviour**
I would expect that `commentBefore` for `# Before C` would stick to `c: hello`.

```yaml
# Before example
example:
  # Before A
  a: world
  # Before B
  b: yaml
  # Before C
  c: hello
```

**Actual behaviour**
```yaml
# Before example
example:
  # Before C
  # Before A
  a: world
  # Before B
  b: yaml
  c: hello
```

**Versions (please complete the following information):**
See codesandbox for all versions.

**Comment by eemeli** [comment]
See the text and note here: https://eemeli.org/yaml/#comments-and-blank-lines

If you'd like to propose a specific change to comment handling, a PR on that could be considered.

**Comment by EloB** [comment]
I've looked into the codebase and won't have the brain capacity to solve this. 🙈 

My ugly workaround ended up like this.
```ts
visit(doc as any, {
    Map(_, node: any, path) {
      if (!node.commentBefore || isSeq(path[path.length - 1])) return
      const { commentBefore } = node
      delete node.commentBefore
      node.items[0].key.commentBefore = commentBefore
    }
  })
```

**Comment by eemeli** [comment]
Yeah, comment assignment is not easy as there's literally no spec and people will have different expectations, in part based on the comment contents. I'm glad you found a solution that works for you, but indeed that isn't something that ought to go into the core library.

**Comment by EloB** [comment]
@eemeli I had a look at the parser and lexer etc but I don't have the time to make proper solution. My client would also kill me  if I invested to much time into this. 😄

**Comment by EloB** [comment]
Based on the variable name `commentBefore` I would argue that the expectation is that assigned to the wrong node but looked at the complexity of the code I can understand it's not so simple to solve.

Thanks for making this library public :)

**Comment by EloB** [comment]
I think the confusion is this example. There is like no concept of "after".

```yaml
# before example
example: # after example
  # before a
  a: 1
  # before b
  b: 2
```

https://codesandbox.io/s/blue-http-jxy6kd?file=/src/index.ts

**Comment by eemeli** [comment]
Consider a slightly smaller example:

```yaml
example:
  # before x
  a: 1
```

Which of the following is that comment "before"?

1. The value assigned to the "example" key, which happens to be a mapping.
2. The `a: 1` key-value pair in the mapping.
3. The `a` key of that pair.
