### ISSUE TITLE
Values are converted from strings to indices in parsing process.

### ISSUE THREAD

**Issue by jamesb93** [eemeli/yaml#505]
**Describe the bug**
I have a basic YAML file:

```yaml
attributes:
    -   name: a1
        digest: First filter coefficient
        description: First allpass filter coefficient.
        size: '1'
        type: float
        value: '4'
        default:
            value: 4
            type: float
            size: 1
    -   name: a2
        digest: Second filter coefficient
        description: Second allpass filter coefficient.
        size: '1'
        type: float
        value: '1'
        default:
            value: 1
            type: float
            size: 1
```

When I parse it this turns out exactly I would expect. I test using this script:

```js
import YAML from 'YAML'
import fs from 'fs'
const testInput = fs.readFileSync('./testin.yaml', 'utf8')
const parsed = YAML.parse(testInput)
console.log(parsed)
```

When I parse the same content from an identical file (albeit in a different directory) inside my VSCode extension that I am developing, the name values are replaced with their index, i.e `a1` becomes `'0'`.

**To Reproduce**
It's a little fussy, but you are able to observe it if you clone the [documax repo](https://github.com/jamesb93/vscode-documax), `git checkout origin/yaml-issues` and enter the debugger through VSCode. Next, open the attached folder ([documax-test-scenario.zip](https://github.com/eemeli/yaml/files/13442554/documax-test-scenario.zip)) in the VSCode that the debugger opened. `Cmd+Shift+P` in the same window and choose the action: `Documax: Generate Output`. 

You will see now in the Debug Console the string which is gathered from `fs.readFileSync` and then the resulting parsed YAML as a JSON object which will have the values clobbered into indices.

**Expected behaviour**
I would expect the name values to not be clobbered.

**Versions (please complete the following information):**

- Environment: [e.g. Node.js 14.7.0 or Chrome 87.0]
- `yaml`: 2.3.4
- `vscode`: ^1.81.0

**Additional context**
I've attached a video showing the problem as I realise the steps to reproduce are annoying and tedious.

https://github.com/eemeli/yaml/assets/13281862/42909f38-2fa2-425b-a552-5f4bb3ebbfe3
