### ISSUE TITLE
the option doubleQuotedMinMultiLineLength for yaml.stringify is not working as intended

### ISSUE THREAD

**Issue by aayshasura** [eemeli/yaml#512]
**Describe the bug**
I am encountering an issue with the `doubleQuotedMinMultiLineLength` option in the yaml.stringify function that doesn't seem to behave as expected.  The option in yaml.stringify `doubleQuotedMinMultiLineLength` is supposed to set min length of the double quoted string that should not be seperated to multiline with `\`. This is'nt an issue for single quoted strings or strings with no quotes in YAML Map representation.

**To Reproduce**
try to parse a yaml doc where a double quoted string is present as a YAMLMap and stringify it with `options = {doubleQuotedMinMultiLineLength: x}`, regardless of what x is the split is always happening from 76th character even though in the docs it is by default 40.

**Expected behaviour**

I expect the doubleQuotedStrings present in the YAMLMap to be split to multiline with escape character `\` only after the length passed in as options. if the  `options = {doubleQuotedMinMultiLineLength: 2}` it should split to multiline after 2 characters and if its 400 it should split into multiline with escape character after 400 characters.

**Versions (please complete the following information):**

- Environment: [e.g. Node.js 14.7.0 or Chrome 87.0]
- `yaml`: [e.g. 1.10.0 or 2.0.0-2]

**Additional context**

**Comment by eemeli** [comment]
Could you provide JS code reproducing the results you think are wrong?

**Comment by aayshasura** [comment]
I am using this inside a language extension server below is code that reads a yaml like language

```
async function updateStandardDataConnector(
  hasuraSettings: HasuraSettings,
  hasuraMetadata: Metadata,
  connection: Connection,
  dataConnector: CachedDataConnector,
  dataConnectorNode: YAMLMap,
  subgraph: string,
  session: HasuraSession
) {

  console.debug("==================================")
  console.debug(stringify(dataConnectorNode,{doubleQuotedMinMultiLineLength: 2}))
  console.debug(stringify(dataConnectorNode))
  console.debug(stringify(dataConnectorNode,{doubleQuotedMinMultiLineLength: 200}))
  console.debug("==================================") 
```

if the file it reads from looks like this
<img width="1098" alt="image" src="https://github.com/eemeli/yaml/assets/109507451/a8886a3b-2ed4-4c8e-9813-6722431a2995">

this is console log
```
==================================
kind: DataConnector
version: v1
definition:
  name: ts_connector
  url:
    singleUrl: "http://localhost:3000/thisurlisveryveryveryveryveryveryveryveryvery\
      veryveryveryverylong"

kind: DataConnector
version: v1
definition:
  name: ts_connector
  url:
    singleUrl: "http://localhost:3000/thisurlisveryveryveryveryveryveryveryveryvery\
      veryveryveryverylong"

kind: DataConnector
version: v1
definition:
  name: ts_connector
  url:
    singleUrl: "http://localhost:3000/thisurlisveryveryveryveryveryveryveryveryvery\
      veryveryveryverylong"

==================================
```
Here you can see that the option is not working no matter what option is passed.
The multiline split with escape "\"  behaviour doesn't happen if the singleUrl here was single -quoted or with no quotes and users are reporting this as a bug.
