### ISSUE TITLE
CST parser fails when file starts with newline

### ISSUE THREAD

**Issue by tiithansen** [eemeli/yaml#515]
**Describe the bug**
If the file starts with new line then parser return only newline token.

Console.log
```
{ type: 'newline', offset: 0, indent: 0, source: '\n' }
```
Instead of:

```
{
  type: 'document',
  offset: 0,
  start: [],
  value: {
    type: 'block-map',
    offset: 0,
    indent: 0,
    items: [ [Object], [Object] ]
  }
}
```

**To Reproduce**
Sample file:

```yaml

configs:
  imagePullPolicy: IfNotPresent          # Test 1
  # Comment
  clusterName: test            # Test
  arr:
  - name: a
    value: 1
  arr2:
  - 1
  # Comment
  createSLOs: true # Comment
  createSecrets: true # Comment
  veryLongString: "dasadsdsadsa,dasasdsdadsaadsads,\
    adsadsaadsdsadsadsadsadsadsadsadsadsa,adsadsdsadsaadsads"
  nested:
    nested: true
testx:
  str: abc
  testy:
    str2: fgy
```

Code:
```
let contents = fs.readFileSync(file).toString()
// Trim new lines from start, CST parser has a bug and cannot handle new lines at the start of the file
//contents = trimStart(contents, '\n')
const [doc] = new Parser().parse(contents)
console.log(doc)
 ```

**Expected behaviour**

Document start should have offset.

**Versions (please complete the following information):**

- Environment: Node 20.5.0
- `yaml`: [2.3.4]
