### ISSUE TITLE
Strange artifacts when stringifying matrices

### ISSUE THREAD

**Issue by LukeHagar** [eemeli/yaml#516]
Howdy,

I'm seeing some strange occurrences when stringifying matrices

Here is the object
```js
{
    matrixMock: [
		[1, 2],
		[3, 4]
	]
}
```

Here is the JSON representation of the schema object
```json
{
  "matrixMock": {
    "type": "array",
    "items": [
      {
        "type": "array",
        "items": [
          {
            "type": "integer",
            "format": "int32",
            "example": 1
          }
        ],
        "example": [1, 2]
      }
    ],
    "example": [
      [1, 2],
      [3, 4]
    ]
  }
}
```

Here is the yaml stringified from the schema object
```yaml
matrixMock:
type: array
items:
  - type: array
    items:
      - type: integer
        format: int32
        example: 1
    example: &a2
      - 1
      - 2
example:
  - *a2
  - - 3
  - 4
```

The `&a2` & `*a2` values in the final yaml are what I am inquiring about.
