### ISSUE TITLE
Exception on parsing the file yaml.parse() that was saved with yaml.stringify() including references

### ISSUE THREAD

**Issue by glodov** [eemeli/yaml#517]
**Describe the bug**
Impossible to parse the references to the data.

**To Reproduce**
Try to parse this yaml data with yaml.parse().
```yaml
unwantedFiles: []
files:
  - name: 404.html
    path: 404.html
    size: 62693
  - name: icomoon.eot
    path: css/fonts/icomoon.eot
    size: 10220
  - name: icomoon.svg
    path: css/fonts/icomoon.svg
    size: 34356
  - name: icomoon.ttf
    path: css/fonts/icomoon.ttf
    size: 10056
  - name: icomoon.woff
    path: css/fonts/icomoon.woff
    size: 10132
  - name: index.css
    path: css/index.css
    size: 411625
  - name: index.css.map
    path: css/index.css.map
    size: 68540
errors: []
filesToUpdate:
  - &a1
    name: 404.html
    path: 404.html
    hash: null
    size: 62304
  - &a2
    name: icomoon.eot
    path: css/fonts/icomoon.eot
    hash: null
    size: 10136
  - &a3
    name: icomoon.svg
    path: css/fonts/icomoon.svg
    hash: null
    size: 34137
  - &a4
    name: icomoon.ttf
    path: css/fonts/icomoon.ttf
    hash: null
    size: 9972
  - &a5
    name: icomoon.woff
    path: css/fonts/icomoon.woff
    hash: null
    size: 10048
  - &a6
    name: index.css
    path: css/index.css
    hash: null
    size: 383426
  - &a7
    name: index.css.map
    path: css/index.css.map
    hash: null
    size: 67632
filesToRemove:
  - css/font-icons.css
toUpdate:
  - *a1
  - *a2
  - *a3
  - *a4
  - *a5
  - *a6
  - *a7
```

Error:
```
TypeError: this.buffer.substring is not a function
    at Lexer.getLine (/Users/yaro/nanoweb/web/node_modules/yaml/dist/parse/lexer.js:208:28)
    at Lexer.parseStream (/Users/yaro/nanoweb/web/node_modules/yaml/dist/parse/lexer.js:244:25)
    at parseStream.next (<anonymous>)
    at Lexer.parseNext (/Users/yaro/nanoweb/web/node_modules/yaml/dist/parse/lexer.js:226:36)
    at parseNext.next (<anonymous>)
    at Lexer.lex (/Users/yaro/nanoweb/web/node_modules/yaml/dist/parse/lexer.js:160:32)
    at lex.next (<anonymous>)
    at Parser.parse (/Users/yaro/nanoweb/web/node_modules/yaml/dist/parse/parser.js:159:20)
    at parse.next (<anonymous>)
    at Composer.compose (/Users/yaro/nanoweb/web/node_modules/yaml/dist/compose/composer.js:130:20)
    at compose.next (<anonymous>)
    at parseDocument (/Users/yaro/nanoweb/web/node_modules/yaml/dist/public-api.js:45:16)
    at Object.parse (/Users/yaro/nanoweb/web/node_modules/yaml/dist/public-api.js:67:17)
    at loadYAML (/Users/yaro/nanoweb/web/src/fs.js:61:17)
    at publish (/Users/yaro/nanoweb/web/publish-send.js:153:17)
    at Object.<anonymous> (/Users/yaro/nanoweb/web/publish-send.js:180:1)
 ```

**Expected behaviour**
A parsed result returned.

**Versions (please complete the following information):**

- Environment: node -v: v20.0.0
- `yaml`: "version": "2.3.4"

**Additional context**
The data has been stringified with the yaml.stringify()
