### ISSUE TITLE
Loosing quotes around a property value in yaml after converting it to json and back to yaml.

### ISSUE THREAD

**Issue by vanessadnguyen** [eemeli/yaml#533]
**Describe the bug**
Loosing quotes around a property value in yaml after converting it to json and back to yaml.

**To Reproduce**
Steps to reproduce the behaviour.

Original yaml entered by users:

```
formatVersion: 1
inputs: {}
resources:
  Cloud_Machine_1:
    type: Cloud.Machine
      properties:
        image: "hnguyenImage"
        flavor: "hnguyenFlavor"
        xxxxx: "yes"
        xxxx1: "no"
        yyyyy: "true"
        yyyy1: "false"

```
We convert it to json using:

`parse(this.yamlContent ?? '', { prettyErrors: false, strict: false })`

We convert the json back to yaml using:

`stringify(json, {
      indent: 2,
      lineWidth: 10000
    });`

The new yaml is losing quotes around property values except "true/false" values. For example, "yes/no" values no longer have double quotes surrounding them.

```
formatVersion: 1
inputs: {}
resources:
  Cloud_Machine_1:
    type: Cloud.Machine
    properties:
      image: hnguyenImage
      flavor: hnguyenFlavor
      xxxxx: yes
      xxxx1: no
      yyyyy: "true"
      yyyy1: "false"

```

**Expected behaviour**
I expect quotes (single quotes or double quotes) to stay the way they were entered originally. Is there any way to configure the parse and stringify method to do this?

**Versions (please complete the following information):**

- Environment: [e.g. Node.js 14.7.0 or Chrome 87.0]
- Node v18.16.0
- `yaml`: version 2.4.1

**Additional context**
