### ISSUE TITLE
Not detecting invalid YAML for multiline strings

### ISSUE THREAD

**Issue by iliapolo** [eemeli/yaml#552]
**Describe the bug**

`YAML.parseAllDocuments` incorrectly parses an invalid YAML.

**To Reproduce**

```ts
import * as YAML from 'yaml';

const objects = YAML.parseAllDocuments(`
properties:
  message:
    description: 'message is a string detailing the encountered error
    during snapshot creation if specified. NOTE: message may be
    logged, and it should not contain sensitive information.'
    type: string
`, {
    version: '1.1',
  });

console.log(JSON.stringify(objects, null, 2));
```

This will print out the following JSON:

```json
    [
      {
        "properties": {
          "message": {
            "description": "message is a string detailing the encountered erro",
            "during snapshot creation if specified. NOTE": "message may be",
            "logged, and it should not contain sensitive information.' type": "string"
          }
        }
      }
    ]
```

**Expected behaviour**

Throw an error

**Versions (please complete the following information):**

- Environment: Node 20
- `yaml`: 1.1

**Additional context**

According to both [yamllint](https://www.yamllint.com/) and the VSCode YAML (by RedHat) extension, is invalid.

![Image](https://github.com/cdk8s-team/cdk8s-core/assets/1428812/87358487-9dbc-4a2e-a015-77614b8be326)
![Image](https://github.com/cdk8s-team/cdk8s-core/assets/1428812/0de040b7-68be-47b8-984b-dec14cee8b1b)

The correct version of this YAML would be:

```yaml
properties:
  message:
    description: 'message is a string detailing the encountered error
     during snapshot creation if specified. NOTE: message may be
     logged, and it should not contain sensitive information.'
    type: string
```

Notice the indentation in the multi-line string.
