### ISSUE TITLE
Incorrect Indentation of Comments when Using `stringify()` Function

### ISSUE THREAD

**Issue by Krzysztof-Kolodziejczyk** [eemeli/yaml#563]
**Describe the bug**
I am experiencing an issue with the stringify() function. The function does not maintain the correct indentation for comments in the output YAML when the input YAML has commented-out sections.

**To Reproduce**
* Provide the following YAML as input to the stringify() function:

```yaml
definitions:
  properties:
    SomeRequest:
        email:
#        sampleEnum:
#          type: string
#          enum:
#            - first value
#            - second one
#            - last
#          default: 'first value'
```

* Run the stringify() function to format the YAML.
```yaml
definitions:
  properties:
    SomeRequest:
      email:
        #        sampleEnum:
        #          type: string
        #          enum:
        #            - first value
        #            - second one
        #            - last
        #          default: 'first value'
```

**Expected behaviour**
The output YAML should maintain the original indentation of the comments as shown in the input:

**Versions (please complete the following information):**

- `yaml`: 2.5.0
