### ISSUE TITLE
Comment handling is off by one

### ISSUE THREAD

**Issue by bodinsamuel** [eemeli/yaml#575]
**Describe the bug**
When dealing with nested object and comments, some comments get pushed into the parent until we reach the last level. Only the last element is correct.

**To Reproduce**

https://codesandbox.io/p/devbox/2cgfk7?file=%2Findex.js%3A15%2C1
> [!NOTE]
> Check terminal

With this yaml
```yaml
# A comment level1
level1:
  # A comment level2
  level2:
    # A comment level3.1
    level3.1: hello
    # A comment level3.2
    level3.2: hello
```

When we `get('level1')` the value of `commentsBefore` is `# A comment level2`, which is incorrect.
Then it's the same for all levels until `level3.1`, this node does not have a comment and `level3.2` have the correct one.
<img width="458" alt="Screenshot 2024-09-09 at 22 51 24" src="https://github.com/user-attachments/assets/fa0df4f4-8bbf-4c7a-810a-47f4b145f20f">

**Expected behaviour**
`commentsBefore` should be assigned to the right node. Or at least it should be off by one consistently. 
I know the support for comment is not complete and an issue was opened/closed before regarding this. I don't think the closing was correct as the behavior is inconsistent.

**Versions (please complete the following information):** 2.5.1

- Environment:Node 20
- `yaml`: [e.g. 1.10.0 or 2.0.0-2]

**Additional context**
