### ISSUE TITLE
Parsing docker-compose.yml

### ISSUE THREAD

**Issue by rmlearney-digicatapult** [eemeli/yaml#626]
Docker-compose files allow hyphenated service names e.g.

```
services:

bob-docker-image:
  image: foo
  volumes: bar
```

But after parsing with `yaml` it renders as a string under `services` and I'm not able to access the value of `image` using `services.bob-docker-image.image`

Could there be something in the documentation about parsing hyphenated keys, or a new function for parsing docker-compose files?
